version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      timezone: Asia/Jakarta
    labels: [dependencies, ci]

  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
      day: monday
      timezone: Asia/Jakarta
    labels: [dependencies, rust]

  - package-ecosystem: npm
    directory: /website
    schedule:
      interval: weekly
      day: monday
      timezone: Asia/Jakarta
    labels: [dependencies, website]
